default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  username: <%= ENV['DBUSER_DEV'] %>
  database: <%= ENV['DBNAME_DEV'] %>
  password: <%= ENV['DBPASS_DEV'] %>

test:
  <<: *default
  username: <%= ENV['DBUSER_TEST'] %>
  database: <%= ENV['DBNAME_TEST'] %>
  password: <%= ENV['DBPASS_TEST'] %>

production:
  <<: *default
  username: <%= ENV['DBUSER_PROD'] %>
  database: <%= ENV['DBNAME_PROD'] %>
  password: <%= ENV['DBPASS_PROD'] %>
